"""Ajout d'une colonne

Revision ID: 2541bdbe0de5
Revises: abd3995f011c
Create Date: 2025-04-21 11:57:51.717171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2541bdbe0de5'
down_revision: Union[str, None] = 'abd3995f011c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications')
    # ### end Alembic commands ###
