"""Initial migration

Revision ID: 8394e9bac040
Revises: 2541bdbe0de5
Create Date: 2025-04-22 00:11:49.765597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8394e9bac040'
down_revision: Union[str, None] = '2541bdbe0de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'color_start')
    op.drop_column('banners', 'color_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('color_end', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('banners', sa.Column('color_start', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
