"""Initial migration

Revision ID: 9e7a7421a26a
Revises: e7b73cda836a
Create Date: 2025-05-12 23:37:58.195187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7a7421a26a'
down_revision: Union[str, None] = 'e7b73cda836a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courier_locations_order_id', table_name='courier_locations')
    op.drop_constraint('courier_locations_order_id_fkey', 'courier_locations', type_='foreignkey')
    op.drop_column('courier_locations', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_locations', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('courier_locations_order_id_fkey', 'courier_locations', 'orders', ['order_id'], ['id'])
    op.create_index('ix_courier_locations_order_id', 'courier_locations', ['order_id'], unique=False)
    # ### end Alembic commands ###
