"""Initial migration

Revision ID: a7455a3b2f80
Revises: e8810d238618
Create Date: 2025-04-29 00:48:17.539930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7455a3b2f80'
down_revision: Union[str, None] = 'e8810d238618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generate_codes',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_generate_codes_email'), 'generate_codes', ['email'], unique=False)
    op.drop_index('ix_password_reset_codes_email', table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='password_reset_codes_pkey')
    )
    op.create_index('ix_password_reset_codes_email', 'password_reset_codes', ['email'], unique=False)
    op.drop_index(op.f('ix_generate_codes_email'), table_name='generate_codes')
    op.drop_table('generate_codes')
    # ### end Alembic commands ###
