"""Initial migration

Revision ID: abd3995f011c
Revises: 673b714f678c
Create Date: 2025-04-16 19:00:56.594381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd3995f011c'
down_revision: Union[str, None] = '673b714f678c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.SMALLINT(), nullable=True))
    op.add_column('users', sa.Column('comment', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('rating_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating_at')
    op.drop_column('users', 'comment')
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
