"""Initial migration

Revision ID: e7b73cda836a
Revises: a7455a3b2f80
Create Date: 2025-05-09 08:28:24.115209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b73cda836a'
down_revision: Union[str, None] = 'a7455a3b2f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_reset_codes_email', table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.add_column('user_devices', sa.Column('app_version', sa.String(), nullable=True))
    op.add_column('user_devices', sa.Column('device_name', sa.String(), nullable=True))
    op.alter_column('user_devices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_devices', 'device_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_devices', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_devices', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_devices', 'device_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_devices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_devices', 'device_name')
    op.drop_column('user_devices', 'app_version')
    op.create_table('password_reset_codes',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='password_reset_codes_pkey')
    )
    op.create_index('ix_password_reset_codes_email', 'password_reset_codes', ['email'], unique=False)
    # ### end Alembic commands ###
