"""Initial migration

Revision ID: e8810d238618
Revises: ba58e284ec51
Create Date: 2025-04-28 23:20:32.357143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8810d238618'
down_revision: Union[str, None] = 'ba58e284ec51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_devices', 'last_used_at')
    # ### end Alembic commands ###
